export const env = import.meta.env;

export const BASENAME = env.VITE_BASENAME;

export const SERVER_ADRESS = env.VITE_SERVER_ADRESS;
export const SERVER_LOGIN_ADRESS = env.VITE_SERVER_LOGIN_ADRESS;
export const SERVER_REGISTER_ADRESS = env.VITE_SERVER_REGISTER_ADRESS;
export const SERVER_GET_ALL_ARTICLES_ADRESS = env.VITE_SERVER_GET_ALL_ARTICLES_ADRESS;
export const SERVER_GET_ARTICLE_ADRESS = env.VITE_SERVER_GET_ARTICLE_ADRESS;
export const SERVER_CREATE_ARTICLE_ADRESS = env.VITE_SERVER_CREATE_ARTICLE_ADRESS;
export const SERVER_EDIT_ARTICLE_ADRESS = env.VITE_SERVER_EDIT_ARTICLE_ADRESS;
export const SERVER_DELETE_ARTICLE_ADRESS = env.VITE_SERVER_DELETE_ARTICLE_ADRESS;
export const SERVER_CATEGORIES_ADRESS = env.VITE_SERVER_CATEGORIES_ADRESS;
export const SERVER_GET_ROLE_ADRESS = env.VITE_SERVER_GET_ROLE_ADRESS;
